CREATE DATABASE IF NOT EXISTS BD_BIBLIOTECA_DIGITAL;
USE BD_BIBLIOTECA_DIGITAL;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    GENERO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL,
    FK_CPF_AUTOR VARCHAR(14),
    FOREIGN KEY (FK_CPF_AUTOR) REFERENCES AUTOR(CPF) ON DELETE CASCADE
);