CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
	USU_LOGIN VARCHAR(255) NOT NULL UNIQUE,
    USU_AREA_ATUAÇAO VARCHAR(500),
    USU_PROFISSAO VARCHAR(200),
    USU_AREA_FORMAÇAO VARCHAR(500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO","CASADO","DIVORCIADO","VIUVU")NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL","MEDIO","SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA  VARCHAR(255) NOT NULL,
    USU_NOME   VARCHAR(255) NOT NULL,
    PRIMARY KEY(USU_CODIGO)
    );

CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENQ_DATA_FINAL DATE,
    ENQ_DATA_INCIAL  DATE NOT NULL,
    ENQ_DESCRIÇAO VARCHAR(500) NOT NULL,
    ENQ_NOME VARCHAR(255) NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    PRIMARY KEY(ENQ_CODIGO),
    FOREIGN KEY(FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER,
    FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY(URE_CODIGO),
    FOREIGN KEY(FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY(FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
	PER_DESCRIÇAO VARCHAR(255) NOT NULL,
    FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY(PER_CODIGO),
    FOREIGN KEY(FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRIÇAO VARCHAR(500) NOT NULL,
    RES_CERTA  VARCHAR(1) NOT NULL,
    FK_PER_CODIGO INTEGER,
    PRIMARY KEY(RES_CODIGO),
    FOREIGN KEY(FK_PER_CODIGO) REFERENCES PERGUNTAS (PER_CODIGO) ON DELETE CASCADE
);

INSERT INTO USUARIO (USU_DATA_CADASTRO,USU_LOGIN,USU_AREA_ATUAÇAO,USU_PROFISSAO,USU_AREA_FORMAÇAO,USU_DATANASC,USU_ESTADO_CIVIL,USU_ESTADO,USU_ESCOLARIDADE,USU_SENHA,USU_EMAIL,USU_NOME)
	VALUES ("2025-10-25","OI","RYAN","TI","TI","2025-10-10","SOLTEIRO","SP","SUPERIOR","RYAN","RYANPORTO811@gmail.com","RYAN");

INSERT INTO ENQUETE (ENQ_DATA_FINAL,	ENQ_DATA_INCIAL ,ENQ_DESCRIÇAO ,ENQ_NOME,FK_USU_CODIGO)
	VALUES("2025-12-12","2025-10-10","jffjf","ryan","1");
    
INSERT INTO USUARIO_RESPONDE_ENQUETE(URE_DATA,	FK_USU_CODIGO,	FK_ENQ_CODIGO)
	VALUES("2025-01-01","1","1");
    
INSERT INTO PERGUNTAS,PER_DESCRIÇAO,FK_ENQ_CODIGO )
		VALUES("HSH","1");

INSERT INTO RESPOSTAS(RES_DESCRIÇAO,	RES_CERTA,	FK_PER_CODIGO)
	VALUES("GGFGGGG","S","2");









SELECT * FROM USUARIO;





