CREATE DATABASE IF NOT EXISTS BD_RESERVAS_AEREAS;
USE BD_RESERVAS_AEREAS;
CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER PRIMARY KEY NOT NULL,
    DATA_VOO VARCHAR(255) NOT NULL,
    VALOR VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER PRIMARY KEY NOT NULL,
    LUGAR VARCHAR(300) NOT NULL,
    FK_ID_VOO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_VOO) REFERENCES VOO(ID) ON DELETE CASCADE,
    FK_CPF_PASSAGEIRO INTEGER NOT NULL,
    FOREIGN KEY (FK_CPF_PASSAGEIRO) REFERENCES PASSAGEIRO(CPF)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF INTEGER PRIMARY KEY NOT NULL,
    IDADE INTEGER NOT NULL
);