CREATE DATABASE IF NOT EXISTS BD_GERENCIADOR_PROJETOS;
USE BD_GERENCIADOR_PROJETOS;

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER PRIMARY KEY NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER PRIMARY KEY NOT NULL,
    QUANTIDADE VARCHAR(400) NOT NULL,
    DESCRICAO VARCHAR(399)NOT NULL,
    FK_ID_PROJETO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_PROJETO) REFERENCES PROJETO(ID) ON DELETE CASCADE,
    FK_CPF_FUNCIONARIO INTEGER NOT NULL,
    FOREIGN KEY (FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIOS(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF INTEGER PRIMARY KEY NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    IDADE INTEGER NOT NULL
);
