CREATE DATABASE IF NOT EXISTS BD_STREAM_VIDEO;
USE BD_STREAM_VIDEO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER PRIMARY KEY NOT NULL, 
    IDADE INTEGER NOT NULL,
    DESCRICAO VARCHAR(450) NOT NULL
);

CREATE TABLE IF NOT EXISTS VIDEO (
	ID INTEGER PRIMARY KEY NOT NULL,
    NOME VARCHAR(500) NOT NULL,
    TEMPO INTEGER NOT NULL,
    FK_ID_CATEGORIA integer NOT NULL,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VISUALIZACAO(
	ID INTEGER PRIMARY KEY NOT NULL,
    INTERACAO INTEGER NOT NULL,
    FK_ID_VIDEO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_VIDEO) REFERENCES  VIDEO(ID) ON DELETE CASCADE
);

