CREATE DATABASE IF NOT EXISTS BD_RES_HOTEL;
USE BD_RES_HOTEL;

CREATE TABLE IF NOT EXISTS HOTEL(
	CNPJ INTEGER PRIMARY KEY NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS HOSPEDE(
	CPF INTEGER PRIMARY KEY NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUARTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NUMERO INTEGER NOT NULL,
    FK_CNPJ_HOTEL INTEGER NOT NULL,
    FOREIGN KEY (FK_CNPJ_HOTEL) REFERENCES HOTEL(CNPJ)ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QUARTO_HOSPEDE(
	ID INTEGER PRIMARY KEY NOT NULL,
    FK_ID_QUARTO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_QUARTO) REFERENCES QUARTO(ID) ON DELETE CASCADE,
    FK_CPF_HOSPEDE INTEGER NOT NULL,
    FOREIGN KEY (FK_CPF_HOSPEDE) REFERENCES HOSPEDE(CPF) ON DELETE CASCADE
);