CREATE DATABASE IF NOT EXISTS BD_MEDICO;
USE BD_MEDICO;

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR(20) PRIMARY KEY,
    ID INTEGER NOT NULL,
    NOME VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM VARCHAR(20) PRIMARY KEY,
    CPF VARCHAR(20) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    ESPECIALIZACAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LUGAR VARCHAR(255) NOT NULL,
    HORA VARCHAR(4) NOT NULL,
    CATEGORIA VARCHAR(255)NOT NULL,
    FK_CPF_PACIENTE VARCHAR(20),
    FK_CRM_MEDICO VARCHAR (20),
    FOREIGN KEY (FK_CPF_PACIENTE) REFERENCES PACIENTE(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_CRM_MEDICO) REFERENCES MEDICO(CRM) ON DELETE CASCADE
);