CREATE DATABASE IF NOT EXISTS BD_ALUGUEL_PRODUTOS;
USE BD_ALUGUEL_PRODUTOS;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    CPF VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    PRECO DECIMAL NOT NULL,
    QTD_DISPONIVEL INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALUGUEL_ID INTEGER AUTO_INCREMENT  PRIMARY KEY,
    DATA_ALUGUEL DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL NOT NULL,
    FK_CLIENTE_ID INTEGER NOT NULL,
    FK_PRODUTO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID) ON DELETE CASCADE,
     FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID) ON DELETE CASCADE
);

-- DML - LINGUAGEM DE MANIPULACAO
-- ISERT - INSERIR
INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME)
VALUES ("EMAIL@EMAIL.COM","19999999","123456789","LEO");

INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME)
VALUES ("RYANPORTO811@GMAIL.COM0","19986121213","549.161.718.02","RYAN");

INSERT INTO CLIENTE (NOME,EMAIL,TELEFONE,CPF)
VALUES ("RYAN","EMAIL@EMAIL.COM","1991919119","1111111111");





-- SELECT - SELECIONAR
SELECT * FROM CLIENTE;




