CREATE DATABASE IF NOT EXISTS BD_ALUGUEL_PRODUTOS;
USE BD_ALUGUEL_PRODUTOS;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    CPF VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    PRECO DECIMAL NOT NULL,
    QTD_DISPONIVEL INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALUGUEL_ID INTEGER AUTO_INCREMENT  PRIMARY KEY,
    DATA_ALUGUEL DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL NOT NULL,
    FK_CLIENTE_ID INTEGER NOT NULL,
    FK_PRODUTO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID) ON DELETE CASCADE,
     FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID) ON DELETE CASCADE
);

-- DML - LINGUAGEM DE MANIPULACAO
-- ISERT - INSERIR
INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME)
VALUES ("EMAIL@EMAIL.COM","19999999","123456789","LEO");

INSERT INTO CLIENTE (EMAIL,TELEFONE,CPF,NOME)
VALUES ("RYANPORTO811@GMAIL.COM0","19986121213","549.161.718.02","RYAN");

INSERT INTO CLIENTE (NOME,EMAIL,TELEFONE,CPF)
VALUES ("RYAN","EMAIL@EMAIL.COM","1991919119","1111111111");

-- SELECT - SELECIONAR
SELECT * FROM CLIENTE;

-- ISERIR - PRODUTOS
INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("MACBOOK_M4","NOTEBOOK","4789","5");

INSERT INTO PRODUTO (NOME,DECRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("PS5","VIDEO_GAME10","5000",10);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("IPHONE17","CELULAR","15000","17");

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("CELTA","CARRO SUPER_POTENTE","35000","1");

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("PS4","VIDEO_GAME","2000","3");

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIEL)
VALUES ("PS1","VIDEO_GAME2","200","1");

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("PS2","VIDEO_GAME3","150","20");

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("PS3","VIDEO GAME4","700","2");

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("XBOX360","VIDEO_GAME5","500","4");

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("BALA","COMIDA","1","100");

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("CHICLETE","COMIDA","1","1000");

SELECT * FROM PRODUTO;

-- ISERIR ALUGUEIS
SELECT *FROM CLIENTE;
SELECT *FROM PRODUTO;

INSERT INTO ALUGUEL (DATA_ALUGUEL,
					DATA_DEVOLUCAO,
                    VALOR_TOTAL,
                    FK_CLIENTE_ID,
                    FK_PRODUTO_ID)
VALUES				(   "2025-09-24",
                    "2025-10-01",
                    7890,
                    3,
                    2);
                    
INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","15000","1","4");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","35000","2","5");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","2000","3","3");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","1","4","8");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","1","1","9");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","500","5","10");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","700","1","11");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","150","2","12");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","500","4","13");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","15000","3","14");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","15000","5","15");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","4789","1","16");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","4789","1","17");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","2000","2","18");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","4789","5","18");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","4789","19","20");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","200","5","21");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","1","5","22");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","200","5","23");

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-09-24","2025-10-01","1","4","24");
                    
SELECT * FROM ALUGUEL;

-- ATUALIZAR REGISTRO
UPDATE PRODUTO
SET    PRECO = 3500
WHERE  PRODUTO_ID=1;

UPDATE PRODUTO
SET    PRECO = 3500
WHERE  PRODUTO_ID=2;

UPDATE PRODUTO
SET    PRECO = 3500
WHERE  PRODUTO_ID=3;

UPDATE PRODUTO
SET    PRECO = 3500
WHERE  PRODUTO_ID=4;

UPDATE PRODUTO
SET    QTD_DISPONIVEL = 33
WHERE  PRODUTO_ID=1;

UPDATE PRODUTO
SET    QTD_DISPONIVEL = 3
WHERE  PRODUTO_ID=2;

UPDATE PRODUTO
SET    QTD_DISPONIVEL = 37
WHERE  PRODUTO_ID=3;

UPDATE PRODUTO
SET    QTD_DISPONIVEL = 36
WHERE  PRODUTO_ID=5;

UPDATE PRODUTO
SET    QTD_DISPONIVEL = 4
WHERE  PRODUTO_ID=6;

UPDATE CLIENTE
SET     EMAIL = "BCHC@GMAIL.COM"
WHERE  CLIENTE_ID=1;



UPDATE CLIENTE
SET     EMAIL = "CHC@GMAIL.COM"
WHERE  CLIENTE_ID=2;

UPDATE ALUGUEL
SET     DATA_DEVOLUCAO ="2025-11-01"  
WHERE  ALUGUEL_ID= 1;

UPDATE ALUGUEL
SET     DATA_DEVOLUCAO ="2025-12-01"  
WHERE  ALUGUEL_ID= 2;

UPDATE ALUGUEL
SET     DATA_DEVOLUCAO ="2025-11-03"  
WHERE  ALUGUEL_ID= 3;

UPDATE ALUGUEL
SET     DATA_DEVOLUCAO ="2026-11-01"  
WHERE  ALUGUEL_ID= 4;

UPDATE ALUGUEL
SET     DATA_DEVOLUCAO ="2025-11-07"  
WHERE  ALUGUEL_ID= 5;

UPDATE ALUGUEL
SET     DATA_DEVOLUCAO ="2025-12-05"  
WHERE  ALUGUEL_ID= 6;

UPDATE ALUGUEL
SET     DATA_DEVOLUCAO ="2028-11-01"  
WHERE  ALUGUEL_ID= 7;

UPDATE ALUGUEL
SET     DATA_DEVOLUCAO ="2027-11-01"  
WHERE  ALUGUEL_ID= 8;

-- apagar um registro (delete)
DELETE FROM CLIENTE WHERE CLIENTE_ID = 1;

DELETE FROM PRODUTO
WHERE  		PRODUTO_ID = 4;
WHERE 		ALUGUEL_ID = 3;


SELECT *
FROM 		CLIENTE
WHERE		CLIENTE_ID = 2;

SELECT NOME,
		PRECO
FROM	PRODUTO
WHERE  PRODUTO_ID = 3;







